version: "3.0"
services:
  vonage-alert:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "vonage-alert"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      INPUT_LABEL: "temperature"
      ALERT_SEVERITY: "broken"
      VONAGE_API: "WhatsApp"
      VONAGE_API_KEY: "abc1234"
      VONAGE_API_SECRET: "abc1234"
      VONAGE_BRAND_NAME: "Weeve Vonage Testing"
      TO_NUMBER: "1234567890"
      SMS_URL: "https://rest.nexmo.com/sms/json"
      MESSAGES_API_URL: "https://messages-sandbox.nexmo.com/v0.1/messages"
      BASE_URL: "https://messages-sandbox.nexmo.com/"
      WHATSAPP_NUMBER: "1234567890"
      FB_SENDER_ID: "1234567890"
      FB_RECIPIENT_ID: "1234567890"
    ports:
      - 80:80
